name: bitcoind-exporter
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read
  packages: write

jobs:
  image:
    name: Build and Push Image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build bitcoind-exporter Image
      id: build-bitcoind-exporter
      uses: redhat-actions/buildah-build@v2
      with:
        image: jmanero/bitcoind-exporter
        tags: latest 24.0 24.0-${{ github.sha }}
        containerfiles: Containerfile

    - name: Push bitcoind-exporter Image to Registry
      id: push
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-bitcoind-exporter.outputs.image }}
        tags: ${{ steps.build-bitcoind-exporter.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
